first_project/first_app/urls.py
from django.conf.urls import url
from django.urls import path
from first_app import views

app_name = "first_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('add_album/', views.album_form, name='album_form'),
    path('add_musician/', views.musician_form, name='musician_form'),
    path('album_list/<int:artist_id>/', views.album_list, name='album_list'),
    path('edit_artist/<int:artist_id>/', views.edit_artist, name = 'edit_artist'),
    path('edit_album/<int:album_id>/', views.edit_album, name= 'edit_album'),
    path('delete_album/<int:album_id>/', views.delete_album, name = 'delete_album'),
    path('delete_artist/<int:artist_id>/', views.delete_musician, name = 'delete_artist'),
]

first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('first_app.urls')),
]

first_project/first_app/models.py
from django.db import models

# Create your models here.

class Musician(models.Model):
    # id = models.AutoField(primary_key=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    instrument = models.CharField(max_length=50)

    def __str__(self):
        return self.first_name + " " + self.last_name

class Album(models.Model):
    # id = models.AutoField(primary_key=True)
    artist = models.ForeignKey(Musician, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    release_date = models.DateField()

    rating = (
    (1,"Worst"),
    (2,"Bad"),
    (3,"Not Bad"),
    (4,"Good"),
    (5,"Excellent!"),
    )

    num_stars = models.IntegerField(choices=rating)

    def __str__(self):
        return self.name + ", Rating: " + str(self.num_stars)

first_project/first_app/forms.py
from django import forms
from django.core import validators
from django.forms import fields
from first_app import models

class MusicianFrom(forms.ModelForm):
    class Meta:
        model = models.Musician
        fields = '__all__'

class AlbumForm(forms.ModelForm):
    release_date = forms.DateField(widget = forms.TextInput(attrs = {'type':'date'}))
    class Meta:
        model = models.Album
        fields = '__all__'

first_project/first_app/views.py
from django.db.models import indexes
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Musician, Album
from first_app import forms
from django.db.models import Avg

# Create your views here.

def index(request):
    musician_list = Musician.objects.order_by('first_name')
    diction ={'title':'Index Page', 'musician_list':musician_list}
    return render(request,'first_app/index.html', context = diction)

def album_list(request, artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    album_list = Album.objects.filter(artist = artist_id)
    artist_rating = Album.objects.filter(artist = artist_id).aggregate(Avg('num_stars'))
    diction = {'title':'List of Album', 'artist_info':artist_info, 'album_list':album_list, 'artist_rating':artist_rating}
    return render(request,'first_app/album_list.html',context = diction)

def musician_form(request):
    form = forms.MusicianFrom()

    if request.method =='POST':
        form = forms.MusicianFrom(request.POST)
        if form.is_valid():
            form.save(commit = True)
            return index(request)

    diction = {'title':'Add Musician','musician_form':form}
    return render(request,'first_app/musician_form.html',context = diction)

def album_form(request):
    form = forms.AlbumForm()

    if request.method =='POST':
        form = forms.AlbumForm(request.POST)
        if form.is_valid():
            form.save(commit = True)
            return index(request)

    diction = {'title':'Add Album', 'album_form':form}
    return render(request, 'first_app/album_form.html', context = diction)

def edit_artist(request,artist_id):
    artist_info = Musician.objects.get(pk=artist_id)
    form = forms.MusicianFrom(instance=artist_info)
    if request.method == 'POST':
        form = forms.MusicianFrom(request.POST, instance=artist_info)
        if form.is_valid():
            form.save(commit=True)
            return album_list(request,artist_id)
    diction = {'edit_form':form}
    return render(request, 'first_app/edit_artist.html', context = diction)

def edit_album(request, album_id):
    album_info = Album.objects.get(pk=album_id)
    form= forms.AlbumForm(instance=album_info)
    diction = {}
    if request.method == 'POST':
        form = forms.AlbumForm(request.POST, instance=album_info)
        if form.is_valid():
            form.save(commit=True)
            diction.update({'sucess_text':"Sucessfully Updated!"})
    diction.update({'edit_form':form})
    diction.update({'album_id':album_id})
    return render(request, 'first_app/edit_album.html', context = diction)

def delete_album(request, album_id):
    album = Album.objects.get(pk=album_id).delete()
    diction = {'delete_success':'Album Delete Successfully!'}
    return render(request, 'first_app/delete_album.html', context = diction)

def delete_musician(request, artist_id):
    artist = Musician.objects.get(pk=artist_id).delete(0)
    diction = {'delete_success':'Musician Delete Successfully!'}
    return render(request, 'first_app/delete_album.html', context = diction)

first_project/templates/first_app/album_form.html
<!doctype html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>This Is Album Form Page</h1>
<form method="POST">
  {{album_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
</form>
{% endblock %}

first_project/templates/first_app/album_list.html
<!doctype html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h4> Artist Name: {{ artist_info }}</h4>
<h4>Instrument: {{ artist_info.instrument }}</h4>
<h4>Artist Rating: {{artist_rating.num_stars__avg}}</h4>
<a href="{% url 'first_app:edit_artist' artist_id=artist_info.id %}" class="btn btn-success btn-sm">Edit</a>
<h1>List of Album:</h1>
<table class="table table-bordered">
  <tr>
    <th>Album Name</th>
    <th>Release Date</th>
    <th>Rating</th>
  </tr>
  {% for album in album_list %}
    <tr>
      <td><a href="{% url 'first_app:edit_album' album_id=album.id %}">{{album.name}}</a></td>
      <td>{{album.release_date}}</td>
      <td>{{album.num_stars}}</td>
    </tr>
  {% endfor %}

</table>
<br>
<a href="{% url 'first_app:delete_artist' artist_id=artist_info.id %}" class="btn btn-danger btn-sm" onclick="return confirm('Delete This Album??')">Delete</a>
{% endblock %}

first_project/templates/first_app/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>{{title}}</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'first_app:index' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:musician_form' %}">Add_Musician</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'first_app:album_form' %}">Add_Album</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <div class="container">

      {% block body_block %}

      {% endblock %}
    </div>

  </body>
</html>

first_project/templates/first_app/delete_album.html
<!doctype html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>Delete Album</h1>
<div class="alert alert-danger">
  {{ delete_success }}
</div>
{% endblock %}

first_project/templates/first_app/edit_album.html
<!doctype html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>Edit Album</h1>
{% if sucess_text %}
<div class="alert alert-success">
  {{ sucess_text }}
</div>
{% endif %}
<form method="POST">
  {{ edit_form.as_p }}
  {% csrf_token %}
  <input type="submit" name="submit" value="Update" class="btn btn-primary btn-sm">
</form>
<br>
<a href="{% url 'first_app:delete_album' album_id=album_id %}" class="btn btn-danger btn-sm" onclick="return confirm('Delete This Album??')">Delete</a>
{% endblock %}

first_project/templates/first_app/edit_artist.html
<!doctype html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>Edit Musiciam</h1>
<form method="POST">
  {{edit_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="Update" class="btn btn-info">
</form>
{% endblock %}

first_project/templates/first_app/index.html
<!doctype html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h3>All Musician List:</h3>
<ul>
{% if musician_list %}
{% for musician in musician_list %}
  <li> <a href="{% url 'first_app:album_list' artist_id=musician.id %}"> {{musician.first_name}} {{musician.last_name}} </a></li>
{% endfor %}
{% else %}
<h3>No Musicianin the list</h3>
{% endif %}
</ul>
{% endblock %}

first_project/templates/first_app/musician_form.html
<!doctype html>
{% extends "first_app/base.html" %}
{% block body_block %}
<h1>This Is Musician Form Page</h1>
<form method="POST">
  {{musician_form.as_p}}
  {% csrf_token %}
  <input type="submit" name="submit" value="Add" class="btn btn-primary btn-sm">
</form>
{% endblock %}